version: "3.9"
services:
  web:
    build: .
    container_name: avtolider_web
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=avtolider_bot.settings
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME:-avtolider_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-root123}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-5432}
      - DOMAIN=${DOMAIN}
      - DOMAIN_WWW=${DOMAIN_WWW}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /opt/migrated_apps/data/avtolider/media:/app/media
      - /opt/migrated_apps/data/avtolider/static:/app/static
      - /opt/migrated_apps/data/avtolider/logs:/app/logs
    ports:
      - "8012:8000"
